/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package newMod;

import editMod.editMod;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author sebastian
 */
public class NewModInit extends javax.swing.JFrame {

    /**
     * Creates new form NewModInit
     */
    public NewModInit() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modAuthor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        modShortDescription = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        modName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("ModName:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 134, 172, 29));

        modAuthor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modAuthorActionPerformed(evt);
            }
        });
        jPanel1.add(modAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 172, 218, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ModAuthor:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 169, 172, 29));

        modShortDescription.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modShortDescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modShortDescriptionActionPerformed(evt);
            }
        });
        jPanel1.add(modShortDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 212, 218, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("ModShortDescription:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 209, 172, 29));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Create mod");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        modName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        modName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modNameActionPerformed(evt);
            }
        });
        jPanel1.add(modName, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 137, 218, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void modAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modAuthorActionPerformed

    private void modShortDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modShortDescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modShortDescriptionActionPerformed

    private void modNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileManager fa = new FileManager();

        try {
            fa.clearFolder();
            fa.createFolders();
            fa.createCapsuleImage();
            fa.createDDBB();
            fa.createTables();
            fa.insertModData(modName.getText(), modAuthor.getText(), modShortDescription.getText());
            fa.createExapleProduct();
            this.dispose();
            editMod em = new editMod();
            em.setVisible(true);
            fa.createExampleProductImage();
        } catch (IOException ex) {

            Logger.getLogger(NewModInit.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewModInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewModInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewModInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewModInit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewModInit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField modAuthor;
    private javax.swing.JTextField modName;
    private javax.swing.JTextField modShortDescription;
    // End of variables declaration//GEN-END:variables
}
